services:
  affshop-strapi:
    container_name: affshop-strapi
    image: reksamur/affshop-strapi:dev
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: affshop-strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - affshop-strapi
    depends_on:
      - affshop-strapiDB

  affshop-strapiDB:
    container_name: affshop-strapiDB
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - affshop-strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - affshop-strapi

  affshop-strapiAdminer:
    container_name: affshop-strapiAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=affshop-strapiDB
    networks:
      - affshop-strapi
    depends_on:
      - affshop-strapiDB

volumes:
  affshop-strapi-data:

networks:
  affshop-strapi:
    name: Affshop-strapi
    driver: bridge
